metrics:
  tags:
    m_application: kotlin-grpc-app
  distribution:
    percentiles-histogram:
      http.server.requests: true
    percentiles:
      all: 0.5, 0.75, 0.95, 0.98, 0.99, 0.999
    slo:
      http.client.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1000ms
      http.server.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1000ms
      grpc.client: 10ms,50ms,100ms,250ms,500ms,750ms,1000ms
      grpc.server: 10ms,50ms,100ms,250ms,500ms,750ms,1000ms

name: kotlin-grpc-app
kafkaConfig:
  topicName: "test"